export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SORT_PRODUCTS_PRICE = "SORT_PRODUCTS_PRICE";
export const FILTER_PRODUCTS_COMPANY = "FILTER_PRODUCTS_COMPANY";
export const ADD_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

