export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SORT_PRODUCTS_PRICE = "SORT_PRODUCTS_PRICE";
export const FILTER_PRODUCTS_COMPANY = "FILTER_PRODUCTS_COMPANY";
export const ADD_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";
export const SHOW_LOGIN = "SHOW_LOGIN";
export const SHOW_REGISTR= "SHOW_REGISTR";
export const CHANGE_AUTH = "CHANGE_AUTH";
export const  ADD_TO_COMPARE = "ADD_TO_COMPARE";
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE"
export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";
export const REMOVE_FROM_COMPARE = "REMOVE_FROM_COMPARE";






