export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SORT_PRODUCTS_PRICE = "SORT_PRODUCTS_PRICE";
export const FILTER_PRODUCTS_COMPANY = "FILTER_PRODUCTS_COMPANY";
export const ADD_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";


